### ISSUE TITLE
TODO: Create a few pages to be rendered with notion data

### ISSUE THREAD

**Issue by vogelino** [technologiestiftung/smart-city-strategie-website#1]
- [x] Integrate [`react-notion-x`](https://github.com/NotionX/react-notion-x)
- [ ] Create a few public notion pages with lots of different content types
- [x] Adapt styles to match another Corporate Identity than the notion CI
- [ ] Add navigation to jump between pages (How ???)
